ALTER TABLE "User" ADD COLUMN "notifyKeys" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN "notifyEvent" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN "notifyFeedback" BOOLEAN NOT NULL DEFAULT false;
